"use client";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { FoodRecipe, makeId, loadRecipes, saveRecipes, SELECTED_KEY, starterRecipes } from "./foodRecipeStore";
import styles from "./RecipeBook.module.css";

const blankRecipe = (): FoodRecipe => ({ id: makeId(), title: "", category: "Backyard BBQ", favorite: false, servings: 4, prepMinutes: 10, cookMinutes: 30, notes: "", ingredients: [{ id: makeId(), quantity: 1, unit: "", name: "" }], steps: [{ id: makeId(), text: "" }] });

export default function RecipeBook() {
  const [recipes, setRecipes] = useState<FoodRecipe[]>([]), [selectedId, setSelectedId] = useState("");
  const [query, setQuery] = useState(""), [category, setCategory] = useState("All"), [favorites, setFavorites] = useState(false);
  const [draft, setDraft] = useState<FoodRecipe | null>(null); const restoreRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const found = loadRecipes(); setRecipes(found); setSelectedId(found[0]?.id || ""); }, []);
  const commit = (next: FoodRecipe[]) => { setRecipes(next); saveRecipes(next); };
  const categories = useMemo(() => ["All", ...Array.from(new Set(recipes.map(r => r.category)))], [recipes]);
  const filtered = useMemo(() => recipes.filter(r => (!favorites || r.favorite) && (category === "All" || r.category === category) && `${r.title} ${r.notes} ${r.ingredients.map(i => i.name).join(" ")}`.toLowerCase().includes(query.toLowerCase())), [recipes, query, category, favorites]);
  const selected = recipes.find(r => r.id === selectedId) || filtered[0];
  const saveDraft = () => { if (!draft || !draft.title.trim()) return; const next = recipes.some(r => r.id === draft.id) ? recipes.map(r => r.id === draft.id ? draft : r) : [draft, ...recipes]; commit(next); setSelectedId(draft.id); setDraft(null); };
  const cook = (recipe: FoodRecipe) => { localStorage.setItem(SELECTED_KEY, JSON.stringify(recipe)); window.location.href = "/food/kitchen"; };
  const backup = () => { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), recipes }, null, 2)], { type: "application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `jaski-recipes-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); };
  const restore = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); const incoming = Array.isArray(parsed) ? parsed : parsed.recipes; if (!Array.isArray(incoming)) throw new Error(); commit(incoming); setSelectedId(incoming[0]?.id || ""); } catch { alert("That file is not a valid Jaski recipe backup."); } event.target.value = ""; };

  return <div className={styles.room}>
    <header className={styles.hero}><div><p>PERSONAL COLLECTION · BACKYARD EDITION</p><h1>Recipe Book.</h1><span>Keep the recipes worth making again.</span></div><div className={styles.heroTools}><button onClick={() => setDraft(blankRecipe())}>＋ Add recipe</button><button onClick={backup}>⇩ Backup</button><button onClick={() => restoreRef.current?.click()}>↥ Restore</button><input ref={restoreRef} hidden type="file" accept="application/json" onChange={restore}/></div></header>
    <div className={styles.toolbar}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search recipes or ingredients…"/><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select><button className={favorites ? styles.active : ""} onClick={() => setFavorites(!favorites)}>★ Favorites</button><span>{filtered.length} recipes · saved locally</span></div>
    <div className={styles.workspace}><aside className={styles.shelf}>{filtered.map(recipe => <button key={recipe.id} className={selected?.id === recipe.id ? styles.selected : ""} onClick={() => setSelectedId(recipe.id)}><b>{recipe.favorite ? "★ " : ""}{recipe.title}</b><span>{recipe.category} · {recipe.cookMinutes} min</span></button>)}{!filtered.length && <p>No recipes match this shelf.</p>}</aside>
      {selected ? <article className={styles.card}><div className={styles.cardTop}><div><p>{selected.category}</p><h2>{selected.title}</h2><span>{selected.notes}</span></div><div className={styles.actions}><button onClick={() => setDraft(structuredClone(selected))}>Edit</button><button onClick={() => commit(recipes.map(r => r.id === selected.id ? {...r, favorite: !r.favorite} : r))}>{selected.favorite ? "★" : "☆"}</button><button onClick={() => { if(confirm(`Delete ${selected.title}?`)) { const next=recipes.filter(r=>r.id!==selected.id); commit(next); setSelectedId(next[0]?.id||""); }}}>Delete</button></div></div>
        <div className={styles.metrics}><span><b>{selected.servings}</b> servings</span><span><b>{selected.prepMinutes}</b> min prep</span><span><b>{selected.cookMinutes}</b> min cook</span></div>
        {selected.bbq && <section className={styles.bbq}><p>KETTLE SETUP</p><div><span><b>Method</b>{selected.bbq.method}</span><span><b>Grill</b>{selected.bbq.grillTarget}</span><span><b>Food</b>{selected.bbq.foodTarget}</span><span><b>Fuel</b>{selected.bbq.fuel}</span></div></section>}
        <div className={styles.columns}><section><h3>Ingredients</h3>{selected.ingredients.map(i => <p key={i.id}>{i.quantity} {i.unit} {i.name}</p>)}</section><section><h3>Method</h3>{selected.steps.map((s,i) => <p key={s.id}><b>{i+1}.</b> {s.text}{s.timerMinutes ? ` · ${s.timerMinutes} min` : ""}</p>)}</section></div>
        <footer><button onClick={() => window.print()}>Print recipe</button><button className={styles.cook} onClick={() => cook(selected)}>Cook this →</button></footer>
      </article> : <article className={styles.empty}><h2>Your recipe shelf is empty.</h2><button onClick={() => { commit(starterRecipes); setSelectedId(starterRecipes[0].id); }}>Restore starter recipes</button></article>}
    </div>
    {draft && <div className={styles.modalBackdrop}><div className={styles.modal}><header><div><p>RECIPE CARD</p><h2>{recipes.some(r=>r.id===draft.id) ? "Edit recipe" : "Add recipe"}</h2></div><button onClick={() => setDraft(null)}>×</button></header><div className={styles.formGrid}>
      <label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Category<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Servings<input type="number" value={draft.servings} onChange={e=>setDraft({...draft,servings:+e.target.value})}/></label><label>Prep minutes<input type="number" value={draft.prepMinutes} onChange={e=>setDraft({...draft,prepMinutes:+e.target.value})}/></label><label>Cook minutes<input type="number" value={draft.cookMinutes} onChange={e=>setDraft({...draft,cookMinutes:+e.target.value})}/></label><label className={styles.wide}>Notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
      <fieldset className={styles.wide}><legend>Ingredients</legend>{draft.ingredients.map((item,index)=><div className={styles.row} key={item.id}><input type="number" step=".25" value={item.quantity} onChange={e=>setDraft({...draft,ingredients:draft.ingredients.map((x,i)=>i===index?{...x,quantity:+e.target.value}:x)})}/><input placeholder="unit" value={item.unit} onChange={e=>setDraft({...draft,ingredients:draft.ingredients.map((x,i)=>i===index?{...x,unit:e.target.value}:x)})}/><input placeholder="ingredient" value={item.name} onChange={e=>setDraft({...draft,ingredients:draft.ingredients.map((x,i)=>i===index?{...x,name:e.target.value}:x)})}/><button onClick={()=>setDraft({...draft,ingredients:draft.ingredients.filter((_,i)=>i!==index)})}>×</button></div>)}<button onClick={()=>setDraft({...draft,ingredients:[...draft.ingredients,{id:makeId(),quantity:1,unit:"",name:""}]})}>＋ ingredient</button></fieldset>
      <fieldset className={styles.wide}><legend>Steps</legend>{draft.steps.map((step,index)=><div className={styles.row} key={step.id}><input className={styles.stepText} value={step.text} placeholder={`Step ${index+1}`} onChange={e=>setDraft({...draft,steps:draft.steps.map((x,i)=>i===index?{...x,text:e.target.value}:x)})}/><input type="number" placeholder="timer min" value={step.timerMinutes||""} onChange={e=>setDraft({...draft,steps:draft.steps.map((x,i)=>i===index?{...x,timerMinutes:+e.target.value||undefined}:x)})}/><button onClick={()=>setDraft({...draft,steps:draft.steps.filter((_,i)=>i!==index)})}>×</button></div>)}<button onClick={()=>setDraft({...draft,steps:[...draft.steps,{id:makeId(),text:""}]})}>＋ step</button></fieldset>
    </div><footer><button onClick={()=>setDraft(null)}>Cancel</button><button className={styles.cook} onClick={saveDraft}>Save recipe</button></footer></div></div>}
  </div>;
}
